# Programme At A Glance {-}
## Monday {#Monday-tbl .unnumbered}
<div style = "overflow-x:auto;">
<table style = "width: 4000px;">
<thead>
<tr>
<th class = "time">Time</th>
<th class = "day">Monday 11<sup>th</sup></th>
</tr>
</thead>
<tbody>
<tr>
<td class = "time">845</td>
<td class = "housekeeping" colspan = "6">Housekeeping,  098 Lecture Theatre (260-098)</td>
</tr>
<tr>
<td class = "time">850</td>
<td class = "open" colspan = "6">Opening Ceremony</td>
</tr>
<tr>
<td class = "time">910</td>
<td class = "keynote" colspan = "6"><a href="Monday.html#talk_201" style = "color: white;">R In Times Of Growing User Base And Data Sizes<br/>Simon Urbanek, AT&T Labs, USA<br/>098 Lecture Theatre (260-098)</a></td>
</tr>
<tr>
<td class = "time">1000</td>
<td class = "mealbreak" colspan = "6">Morning Tea (30 minutes)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1030</td>
<td class = "contributed"><a href="Monday.html#talk_022" style = "color: black;">Robust Principal Expectile Component Analysis<br/>Liang-Ching Lin</a></td>
<td class = "contributed"><a href="Monday.html#talk_002" style = "color: black;">Effect Of Area Level Deprivation On Body Mass Index: Analysis Of NZ Health Surveys<br/>Andrew Adiguna Halim</a></td>
<td class = "contributed"><a href="Monday.html#talk_012" style = "color: black;">Calendar-Based Graphics For Visualising People's Daily Schedules<br/>Earo Wang</a></td>
<td class = "contributed"><a href="Monday.html#talk_036" style = "color: black;">Nonparametric Test For Volatility In Clustered Multiple Time Series<br/>Paolo Victor Redondo</a></td>
<td class = "contributed"><a href="Monday.html#talk_122" style = "color: black;">IGESS: A Statistical Approach To Integrating Individual Level Genotype Data And Summary Statistics In Genome Wide Association Studies<br/>Xiang Wan</a></td>
<td class = "contributed"><a href="Monday.html#talk_128" style = "color: black;">Author Name Identification For Evaluating Research Performance Of Institutes<br/>Tomokazu Fujino</a></td>
</tr>
<tr>
<td class = "time">1050</td>
<td class = "contributed"><a href="Monday.html#talk_155" style = "color: black;">A Computational Tool For Detecting Copy Number Variations From Whole Genome And Targeted Exome Sequencing<br/>Yu-Chung Wei</a></td>
<td class = "contributed"><a href="Monday.html#talk_021" style = "color: black;">Clustering Using Nonparametric Mixtures And Mode Identification<br/>Shengwei Hu</a></td>
<td class = "contributed"><a href="Monday.html#talk_037" style = "color: black;">Bayesian Curve Fitting For Discontinuous Function Using Overcomplete Representation With Multiple Kernels<br/>Youngseon Lee</a></td>
<td class = "contributed"><a href="Monday.html#talk_030" style = "color: black;">Estimation Of A Semiparametric Spatiotemporal Models With Mixed Frequency<br/>Erniel Barrios</a></td>
<td class = "contributed"><a href="Monday.html#talk_148" style = "color: black;">LSMM: A Statistical Approach To Integrating Functional Annotations With Genome-Wide Association Studies<br/>Jingsi Ming</a></td>
<td class = "contributed"><a href="Monday.html#talk_187" style = "color: black;">A Study Of The Influence Of Articles In The Large-Scale Citation Network<br/>Frederick Kin Hing Phoa</a></td>
</tr>
<tr>
<td class = "time">1110</td>
<td class = "contributed"><a href="Monday.html#talk_203" style = "color: black;">Estimating Links Of A Network From Time To Event Data<br/>Tso‐Jung Yen</a></td>
<td class = "contributed"><a href="Monday.html#talk_023" style = "color: black;">Estimation Of A High-Dimensional Covariance Matrix<br/>Xiangjie Xue</a></td>
<td class = "contributed"><a href="Monday.html#talk_055" style = "color: black;">Innovative Bayesian Estimation In The von Mises Distribution<br/>Yuta Kamiya</a></td>
<td class = "contributed"><a href="Monday.html#talk_035" style = "color: black;">Evidence Of Climate Change From Nonparametric Change-Point Analysis<br/>Angela Nalica</a></td>
<td class = "contributed"><a href="Monday.html#talk_161" style = "color: black;">Joint Analysis Of Individual Level Genotype Data And Summary Statistics By Leveraging Pleiotropy<br/>Can Yang</a></td>
<td class = "contributed"><a href="Monday.html#talk_157" style = "color: black;">An Advanced Approach For Time Series Forecasting Using Deep Learning<br/>Balaram Panda</a></td>
</tr>
<tr>
<td class = "time">1130</td>
<td class = "contributed"><a href="Monday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Monday.html#talk_029" style = "color: black;">Genetic Map Estimation Using Hidden Markov Models In The Presence Of Partially Observed Information<br/>Timothy Bilton</a></td>
<td class = "contributed"><a href="Monday.html#talk_076" style = "color: black;">A Simple Method For Grouping Patients Based On Historical Doses<br/>Shengli Tzeng</a></td>
<td class = "contributed"><a href="Monday.html#talk_065" style = "color: black;">Semiparametric Mixed Analysis Of Covariance Model<br/>Joseph Ryan Lansangan</a></td>
<td class = "contributed"><a href="Monday.html#talk_125" style = "color: black;">Adaptive False Discovery Rate Regression With Application In Integrative Analysis Of Large-Scale Genomic Data<br/>Can Yang</a></td>
<td class = "contributed"><a href="Monday.html#talk_159" style = "color: black;">Structure Of Members In The Organization To Induce Innovation: Quantitatively Analyze The Capability Of The Organization<br/>Yuji Mizukami</a></td>
</tr>
<tr>
<td class = "time">1150</td>
<td class = "contributed"><a href="Monday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Monday.html#talk_031" style = "color: black;">Vector Generalized Linear Time Series Models<br/>Victor Miranda</a></td>
<td class = "contributed"><a href="Monday.html#talk_093" style = "color: black;">Local Canonical Correlation Analysis For Multimodal Labeled Data<br/>Seigo Mizutani</a></td>
<td class = "contributed"><a href="Monday.html#talk_100" style = "color: black;">A Practitioners Guide To Deep Learning For Predictive Analytics On Structured Data<br/>Balaram Panda</a></td>
<td class = "contributed"><a href="Monday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Monday.html#talk_190" style = "color: black;">Clustering Of Research Subject Based On Stochastic Block Model<br/>Keisuke Honda</a></td>
</tr>
<tr>
<td class = "time">1210</td>
<td class = "mealbreak" colspan = "6">Group photo, followed by Lunch (1 hour 10 minutes)</td>
</tr>
<tr>
<td class = "time">1320</td>
<td class = "keynote" colspan = "6"><a href="Monday.html#talk_200" style = "color: white;">Zen And The aRt Of Workflow Maintenance<br/>Jenny Bryan, University of British Columbia<br/>098 Lecture Theatre (260-098)</a></td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1410</td>
<td class = "contributed"><a href="Monday.html#talk_079" style = "color: black;">Canonical Covariance Analysis For Mixed Numerical And Categorical Three-Way Three-Mode Data<br/>Jun Tsuchida</a></td>
<td class = "contributed"><a href="Monday.html#talk_038" style = "color: black;">Variable Selection Algorithms<br/>Fangyao Li</a></td>
<td class = "contributed"><a href="Monday.html#talk_094" style = "color: black;">Estimating Causal Structures For Continuous And Discrete Variables<br/>Mako Yamayoshi</a></td>
<td class = "contributed"><a href="Monday.html#talk_010" style = "color: black;">Incorporating Genetic Networks Into Case-Control Association Studies With High-Dimensional DNA Methylation Data<br/>Hokeun Sun</a></td>
<td class = "contributed"><a href="Monday.html#talk_015" style = "color: black;">Adaptive Model Checking For Functional Single-Index Models<br/>Zhenghui Feng</a></td>
<td class = "contributed"><a href="Monday.html#talk_177" style = "color: black;">Mobile Learning In Teaching Bioinformatics For Medical Doctors<br/>Taerim Lee and Jung Jin Lee</a></td>
</tr>
<tr>
<td class = "time">1430</td>
<td class = "contributed"><a href="Monday.html#talk_034" style = "color: black;">On Optimal Group Testing Designs: Prevalence Estimation, Cost Considerations, And Dilution Effects<br/>Shih-Hao Huang</a></td>
<td class = "contributed"><a href="Monday.html#talk_041" style = "color: black;">The Use Of Bayesian Networks In Grape Yield Prediction<br/>Rory Ellis</a></td>
<td class = "contributed"><a href="Monday.html#talk_101" style = "color: black;">Pattern Prediction For Time Series Data With Change Points<br/>Satoshi Goto</a></td>
<td class = "contributed"><a href="Monday.html#talk_018" style = "color: black;">Test For Genomic Imprinting Effects On The X Chromosome<br/>Wing Kam Fung</a></td>
<td class = "contributed"><a href="Monday.html#talk_027" style = "color: black;">Fluctuation Reduction Of Value-At-Risk Estimation And Its Applications<br/>Shih-Feng Huang</a></td>
<td class = "contributed"><a href="Monday.html#talk_204" style = "color: black;">E-Learning Courses On Introductory Statistics Using Interactive Educational Tools<br/>Kazunori Yamaguchi</a></td>
</tr>
<tr>
<td class = "time">1450</td>
<td class = "contributed"><a href="Monday.html#talk_061" style = "color: black;">Estimation Of Animal Density From Acoustic Detections<br/>Ben Stevenson</a></td>
<td class = "contributed"><a href="Monday.html#talk_045" style = "color: black;">Mixed Models For Complex Survey Data<br/>Xudong Huang</a></td>
<td class = "contributed"><a href="Monday.html#talk_102" style = "color: black;">Regression With Random Effects For Analysing Correlated Survival Data: Application To Disease Recurrences<br/>Richard Tawiah</a></td>
<td class = "contributed"><a href="Monday.html#talk_085" style = "color: black;">Genetic Predictors Underlying Long-Term Cognitive Recovery Following Mild Traumatic Brain Injury<br/>Priya Parmar</a></td>
<td class = "contributed"><a href="Monday.html#talk_049" style = "color: black;">Bayesian Structure Selection For Vector Autoregression Model<br/>Ray-Bing Chen</a></td>
<td class = "contributed"><a href="Monday.html#talk_182" style = "color: black;">Three-Dimensional Data Visualization Education With Virtual Reality<br/>Dae-Heung Jang</a></td>
</tr>
<tr>
<td class = "time">1510</td>
<td class = "contributed"><a href="Monday.html#talk_146" style = "color: black;">Talk Data To Me<br/>Lisa Hall</a></td>
<td class = "contributed"><a href="Monday.html#talk_052" style = "color: black;">Smooth Nonparametric Regression Under Shape Restrictions<br/>Hongbin Guo</a></td>
<td class = "contributed"><a href="Monday.html#talk_130" style = "color: black;">Elastic-Band Transform: A New Approach To Multiscale Visualization<br/>Hee-Seok Oh</a></td>
<td class = "contributed"><a href="Monday.html#talk_180" style = "color: black;">Meta-Analytic Principal Component Analysis In Integrative Omics Application<br/>Sunghwan Kim</a></td>
<td class = "contributed"><a href="Monday.html#talk_081" style = "color: black;">Flight To Relative Safety: Learning From A No-Arbitrage Network Of Yield Curves Model Of The Euro Area<br/>Linlin Niu</a></td>
<td class = "contributed"><a href="Monday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1530</td>
<td class = "mealbreak" colspan = "6">Afternoon tea (30 minutes)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1600</td>
<td class = "contributed"><a href="Monday.html#talk_020" style = "color: black;">Bayesian Analyses Of Non-Homogeneous Gaussian Hidden Markov Models<br/>Shin Sato</a></td>
<td class = "contributed"><a href="Monday.html#talk_060" style = "color: black;">Robustness Of Temperature Reconstruction For Past 500 Years<br/>Yu Yang</a></td>
<td class = "contributed"><a href="Monday.html#talk_139" style = "color: black;">Nonparametric Causal Inference By The Kernel Method<br/>Yuchi Matsuoka</a></td>
<td class = "contributed"><a href="Monday.html#talk_019" style = "color: black;">A Unified Regularized Group PLS Algorithm Scalable To Big Data<br/>Pierre Lafaye de Micheaux</a></td>
<td class = "contributed"><a href="Monday.html#talk_033" style = "color: black;">Evaluation Of Spatial Cluster Detection Method Based On All Geographical Linkage Patterns<br/>Fumio Ishioka</a></td>
<td class = "contributed"><a href="Monday.html#talk_134" style = "color: black;">Scoring Rules For Prediction And Classification Challenges<br/>Matt Parry</a></td>
</tr>
<tr>
<td class = "time">1620</td>
<td class = "contributed"><a href="Monday.html#talk_095" style = "color: black;">Meta-Analysis With Symbolic Data Analysis And Its Application For Clinical Data<br/>Ryo Takagi</a></td>
<td class = "contributed"><a href="Monday.html#talk_077" style = "color: black;">Real-Time Transit Network Modelling For Improved Arrival Time Predictions<br/>Tom Elliott</a></td>
<td class = "contributed"><a href="Monday.html#talk_149" style = "color: black;">Visualization And Statistical Modeling Of Financial Big Data<br/>Masayuki Jimichi</a></td>
<td class = "contributed"><a href="Monday.html#talk_140" style = "color: black;">Sparse Group-Subgroup Partial Least Squares With Application To Genomic Data<br/>Matthew Sutton</a></td>
<td class = "contributed"><a href="Monday.html#talk_040" style = "color: black;">Genetic Approach And Statistical Approach For Association Study On DNA Data<br/>Makoto Tomita</a></td>
<td class = "contributed"><a href="Monday.html#talk_150" style = "color: black;">Modeling Of Document Abstraction Using Association Rule Based Characterization<br/>Ken Nittono</a></td>
</tr>
<tr>
<td class = "time">1640</td>
<td class = "contributed"><a href="Monday.html#talk_088" style = "color: black;">Bayesian Static Parameter Inference For Partially Observed Stochastic Systems<br/>Yaxian Xu</a></td>
<td class = "contributed"><a href="Monday.html#talk_080" style = "color: black;">Bayesian Survival Analysis Of Batsmen In Test Cricket<br/>Oliver Stevenson</a></td>
<td class = "contributed"><a href="Monday.html#talk_142" style = "color: black;">Covariate Discretisation On Big Data<br/>Hon Hwang</a></td>
<td class = "contributed"><a href="Monday.html#talk_092" style = "color: black;">BIG-SIR A Sliced Inverse Regression Approach For Massive Data<br/>Benoit Liquet</a></td>
<td class = "contributed"><a href="Monday.html#talk_087" style = "color: black;">Symbolic Data Analytical Approach To Unauthorized-Access Logs<br/>Hiroyuki Minami</a></td>
<td class = "contributed"><a href="Monday.html#talk_192" style = "color: black;">My Knee Still Hurts; The Statistical Pathway To The Development Of A Clinical Decision Aid<br/>Robert Borotkanics</a></td>
</tr>
</tbody>
</table>
</div>
## Tuesday {#Tuesday-tbl .unnumbered}
<div style = "overflow-x:auto;">
<table style = "width: 4000px;">
<thead>
<tr>
<th class = "time">Time</th>
<th class = "day">Tuesday 12<sup>th</sup></th>
</tr>
</thead>
<tbody>
<tr>
<td class = "time">900</td>
<td class = "housekeeping" colspan = "6">Housekeeping,  098 Lecture Theatre (260-098)</td>
</tr>
<tr>
<td class = "time">910</td>
<td class = "keynote" colspan = "6"><a href="Tuesday.html#talk_198" style = "color: white;">Could Do Better &hellip; A Report Card For Statistical Computing<br/>Ross Ihaka, University of Auckland<br/>098 Lecture Theatre (260-098)</a></td>
</tr>
<tr>
<td class = "time">1000</td>
<td class = "mealbreak" colspan = "6">Morning Tea (30 minutes)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1030</td>
<td class = "contributed"><a href="Tuesday.html#talk_025" style = "color: black;">R&amp;D Policy Regimes In France: New Evidence From A Spatio-Temporal Analysis<br/>Benjamin Montmartin</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_084" style = "color: black;">Analysing Scientific Collaborations Of New Zealand Institutions Using Scopus Bibliometric Data<br/>Samin Aref</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_170" style = "color: black;">Family Structure And Academic Achievements Of High School Students In Tonga<br/>Losana Vao Latu Latu</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_017" style = "color: black;">Analysis Of Multivariate Binary Longitudinal Data: Metabolic Syndrome During Menopausal Transition<br/>Geoff Jones</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_169" style = "color: black;">Clustering Of Curves On A Spatial Domain Using A Bayesian Partitioning Model<br/>Chae Young Lim</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_044" style = "color: black;">The Uncomfortable Entrepreneurs: Bad Working Conditions And Entrepreneurial Commitment<br/>Catherine Laffineur</a></td>
</tr>
<tr>
<td class = "time">1050</td>
<td class = "contributed"><a href="Tuesday.html#talk_028" style = "color: black;">Spatial Surveillance With Scan Statistics By Controlling The False Discovery Rate<br/>Xun Xiao</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_113" style = "color: black;">Statistical Models For The Source Attribution Of Zoonotic Diseases: A Study Of Campylobacteriosis<br/>Sih-Jing Liao</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_039" style = "color: black;">Towards An Informal Test For Goodness-Of-Fit<br/>Anna Fergusson</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_024" style = "color: black;">Identifying Clusters Of Patients With Diabetes Using A Markov Birth-Death Process<br/>Mugdha Manda</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_174" style = "color: black;">Bayesian Temporal Density Estimation Using Autoregressive Species Sampling Models<br/>Seongil Jo</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_047" style = "color: black;">How Does The Textile Set Describe Geometric Structures Of Data?<br/>Ushio Tanaka</a></td>
</tr>
<tr>
<td class = "time">1110</td>
<td class = "contributed"><a href="Tuesday.html#talk_046" style = "color: black;">Intensity Estimation Of Spatial Point Processes Based On Area-Aggregated Data<br/>Hsin-Cheng Huang</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_115" style = "color: black;">Bayesian Inference For Population Attributable Measures<br/>Sarah Pirikahu</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_147" style = "color: black;">An Information Criterion For Prediction With Auxiliary Variables Under Covariate Shift<br/>Takahiro Ido</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_118" style = "color: black;">Analysis Of A Brief Telephone Intervention For Problem Gambling And Examining The Impact On Co-Existing Depression?<br/>Nick Garrett</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_175" style = "color: black;">Prior-Based Bayesian Information Criterion<br/>Woncheol Jang</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_086" style = "color: black;">Correlated Defaults With A Distance To Default<br/>Chu-Lan Kao</a></td>
</tr>
<tr>
<td class = "time">1130</td>
<td class = "contributed"><a href="Tuesday.html#talk_067" style = "color: black;">Geographically Weighted Principal Component Analysis For Spatio-Temporal Statistical Dataset<br/>Narumasa Tsutsumida</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_116" style = "color: black;">Dimensionality Reduction Of Multivariate Data For Bayesian Analysis<br/>Anjali Gupta</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_016" style = "color: black;">An EWMA Chart For Monitoring Covariance Matrix Based On Dissimilarity Index<br/>Longcheen Huwang</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_162" style = "color: black;">Adjusting For Linkage Bias In The Analysis Of Record-Linked Data<br/>Patrick Graham</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_176" style = "color: black;">Bayesian Semiparametric Hierarchical Models For Longitudinal Data Analysis With Application To Dose-Response Studies<br/>Taeryon Choi</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_091" style = "color: black;">Optimizing Junior Rugby Weight Limits<br/>Ankit Patel</a></td>
</tr>
<tr>
<td class = "time">1150</td>
<td class = "contributed"><a href="Tuesday.html#talk_144" style = "color: black;">Spatial Scan Statistics For Matched Case-Control Data<br/>Inkyung Jung</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_124" style = "color: black;">Whitebait In All Its Varieties: One Fish, Two Fish, Three, Four, Five Fish.<br/>Bridget Armstrong</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_191" style = "color: black;">Latent Variable Models And Multivariate Binomial Data<br/>John Holmes</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_193" style = "color: black;">Asking About Sex In General Health Surveys: Comparing The Methods And Findings Of The 2010 Health Survey For England With Those Of The Third National Survey Of Sexual Attitudes And Lifestyles<br/>Philip Prah</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_132" style = "color: black;">Bayesian Continuous Space-Time Model Of Burglaries<br/>Paul Brown</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_164" style = "color: black;">Tolerance Limits For The Reliability Of Semiconductor Devices Using Longitudinal Data<br/>Thomas Nowak</a></td>
</tr>
<tr>
<td class = "time">1210</td>
<td class = "mealbreak" colspan = "6">Lunch (1 hour 10 minutes)</td>
</tr>
<tr>
<td class = "time">1320</td>
<td class = "keynote" colspan = "6"><a href="Tuesday.html#talk_NA" style = "color: white;">Session In Memory Of Alastair John Scott<br/>1320hrs-1530hrs<br/>Speakers: Professor John Neuhaus (UCSF), Professor Chris Wild, Professor Alan Lee, Professor Thomas Lumley<br/><br/><br/><br/><br/><br/></a></td>
</tr>
<tr>
<td class = "time">1530</td>
<td class = "mealbreak" colspan = "6">Afternoon tea (30 minutes)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1600</td>
<td class = "contributed"><a href="Tuesday.html#talk_189" style = "color: black;">Model-Checking For Regressions: A Local Smoothing-Based Global Smoothing Test<br/>Lingzhu Li</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_135" style = "color: black;">Breeding Value Estimation In Partially-Genotyped Populations<br/>Alastair Lamont</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_151" style = "color: black;">BIVAS: A Scalable Bayesian Method For Bi-Level Variable Selection<br/>Mingxuan Cai</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_078" style = "color: black;">Ranking Potential Shoplifters In Real Time<br/>Barry McDonald</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_073" style = "color: black;">Two Stage Approach To Data-Driven Subgroup Identification In Clinical Trials<br/>Toshio Shimokawa</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_013" style = "color: black;">Estimation And Prediction For A Distribution With Bathtub Shape Under Progressive First Failure Censoring<br/>Tanmay Kayal</a></td>
</tr>
<tr>
<td class = "time">1620</td>
<td class = "contributed"><a href="Tuesday.html#talk_184" style = "color: black;">Inverse Regression For Multivariate Functional Data<br/>Ci-Ren Jiang</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_138" style = "color: black;">Including Covariate Estimation Error When Predicting Species Distributions: A Simulation Exercise Using Template Model Builder<br/>Andrea Havron</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_074" style = "color: black;">Adjusted Adaptive Index Model For Binary Response<br/>Ke Wan</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_109" style = "color: black;">Factors Influencing On Growth Of Garments Industry In Bangladesh<br/>Md. Shahidul Islam</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_103" style = "color: black;">Comparison Of Exact And Approximate Testing Procedures In Clinical Trials With Multiple Binary Endpoints<br/>Takuma Ishihara</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_014" style = "color: black;">Bayesian Optimum Warranty Length Under Type-II Unified Hybrid Censoring Scheme<br/>Tanmay Sen</a></td>
</tr>
<tr>
<td class = "time">1640</td>
<td class = "contributed"><a href="Tuesday.html#talk_185" style = "color: black;">Multiple Function-On-Function Linear Regression With Application To Weather Forecast Calibration<br/>Lu-Hung Chen</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_156" style = "color: black;">Modelling The Distribution Of Lifetime Using Compound Time-Homogenous Poisson Process<br/>Kien Tran</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_072" style = "color: black;">Detecting Change-Points In The Stress-Strength Reliability P(X&LT;Y)<br/>Hang Xu</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_111" style = "color: black;">New Zealand Crime And Victims Survey: Filling The Knowledge Gap<br/>Tianying Chu</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_127" style = "color: black;">Missing Data In Randomised Control Trials: Stepped Multiple Imputation<br/>Rose Sisk</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1700</td>
<td class = "contributed"><a href="Tuesday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Tuesday.html#talk_NA" style = "color: black;">NZSA Annual General Meeting<br/>1700 - 1815</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_NA" style = "color: black;">IASC General Assembly<br/>1700-1815</a></td>
<td class = "contributed"><a href="Tuesday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Tuesday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Tuesday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1830</td>
<td class = "mealbreak" colspan = "6">Conference Dinner<br/>Owen G Glenn Building Foyer<br/>Level 1, 20 Grafton Road<br/>1830-2230</td>
</tr>
</tbody>
</table>
</div>
## Wednesday {#Wednesday-tbl .unnumbered}
<div style = "overflow-x:auto;">
<table style = "width: 4000px;">
<thead>
<tr>
<th class = "time">Time</th>
<th class = "day">Wednesday 13<sup>th</sup></th>
</tr>
</thead>
<tbody>
<tr>
<td class = "time">900</td>
<td class = "housekeeping" colspan = "6">Housekeeping</td>
</tr>
<tr>
<td class = "time">910</td>
<td class = "keynote" colspan = "6"><a href="Wednesday.html#talk_NA" style = "color: white;">Professor Michael Ferris, University Of Wisconsin - Madison, USA<br/>ORSNZ Keynote<br/>098 Lecture Theatre (260-098)</a></td>
</tr>
<tr>
<td class = "time">1000</td>
<td class = "mealbreak" colspan = "6">Morning Tea (30 minutes)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1030</td>
<td class = "contributed"><a href="Wednesday.html#talk_009" style = "color: black;">Promoting Your R Package<br/>Hadley Wickham</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_158" style = "color: black;">A Smoothing Filter Modelling Approach For Time Series<br/>Marco Reale</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_003" style = "color: black;">Online Learning For Bayesian Nonparametrics: Weakly Conjugate Approximation<br/>Yongdai Kim</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_050" style = "color: black;">Improving The Production Cycle At Stats NZ With Rstudio<br/>Gareth Minshall</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_006" style = "color: black;">Sparse Common Component Analysis<br/>Heewon Park</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_062" style = "color: black;">Random Search Global Optimization Using Random Forests<br/>Blair Robertson</a></td>
</tr>
<tr>
<td class = "time">1050</td>
<td class = "contributed"><a href="Wednesday.html#talk_032" style = "color: black;">gridSVG: Then And Now<br/>Paul Murrell</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_188" style = "color: black;">Probabilistic Outlier Detection And Visualization Of Smart Meter Data<br/>Rob Hyndman</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_004" style = "color: black;">The Joint Models For Nonlinear Longitudinal And Time-To-Event Data Using Penalized Splines: A Bayesian Approach<br/>Thi Thu Huong Pham</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_053" style = "color: black;">R – A Powerful Analysis Tool To Improve Official Statistics In Romania<br/>Nicoleta Caragea</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_063" style = "color: black;">A Max-Type Multivariate Two-Sample Baumgartner Statistic<br/>Hidetoshi Murakami</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_075" style = "color: black;">Dimension Reduction For Classification Of High-Dimensional Data By Stepwise SVM<br/>Elizabeth Chou</a></td>
</tr>
<tr>
<td class = "time">1110</td>
<td class = "contributed"><a href="Wednesday.html#talk_066" style = "color: black;">Bringing Multimix From Fortran To R<br/>Murray Jorgensen</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_007" style = "color: black;">Specification Of GARCH Model Under Asymmetric Error Innovations<br/>Oyebimpe Adeniji</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_064" style = "color: black;">Performance Of Bayesian Credible Interval For Binomial Proportion Using Logit Transformation<br/>Toru Ogura</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_054" style = "color: black;">Statistical Disclosure Control With R: Traditional Methods And Synthetic Data<br/>Matthias Templ</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_071" style = "color: black;">Simultaneous Test For Mean Vectors And Covariance Matrices In High-Dimensional Settings<br/>Takahiro Nishiyama</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_096" style = "color: black;">Deep Learning High-Dimensional Covariance Matrices<br/>Philip Yu</a></td>
</tr>
<tr>
<td class = "time">1130</td>
<td class = "contributed"><a href="Wednesday.html#talk_141" style = "color: black;">R In Industry – Application On Pipe Renewal Planning<br/>Glenn Thomas</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_059" style = "color: black;">Empirical Comparison Of Some Algorithms For Automatic Univariate ARMA Modeling Using Rcmdrplugin.SPSS<br/>Dedi Rosadi</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Wednesday.html#talk_098" style = "color: black;">Imputation Of The 2016 Economic Census For Business Activity In Japan<br/>Kazumi Wada</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_108" style = "color: black;">High Dimensional Asymptotics For The Naive Canonical Correlation Coefficient<br/>Mitsuru Tamatani</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_105" style = "color: black;">Applying Active Learning Procedure To Drug Consumption Data<br/>Yuan-Chin Chang</a></td>
</tr>
<tr>
<td class = "time">1150</td>
<td class = "contributed"><a href="Wednesday.html#talk_194" style = "color: black;">R For Everything<br/>Jared Lander</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_143" style = "color: black;">R Package For New Two-Stage Methods In Forecasting Time Series With Multiple Seasonality<br/>Shubhabrata Das</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Wednesday.html#talk_112" style = "color: black;">Analysis Of Official Microdata Using Secure Statistical Computation System<br/>Kiyomi Shirakawa</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Wednesday.html#talk_011" style = "color: black;">Presenting Flexi, A Statistical Program For Fitting Variance Models<br/>Martin Upsdell</a></td>
</tr>
<tr>
<td class = "time">1210</td>
<td class = "mealbreak" colspan = "6">Lunch (1 hour 10 minutes)</td>
</tr>
<tr>
<td class = "time">1320</td>
<td class = "keynote" colspan = "6"><a href="Wednesday.html#talk_197" style = "color: white;">Space And Circular Time Log Gaussian Cox Processes With Application To Crime Event Data<br/>Alan Gelfand, Duke University<br/>098 Lecture Theatre (260-098)</a></td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">Case Room 1(260-005)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1410</td>
<td class = "contributed"><a href="Wednesday.html#talk_056" style = "color: black;">Cluster-Wise Regression Models Combined By A Quasi-Linear Function<br/>Kenichi Hayashi</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_171" style = "color: black;">Hierarchical Structural Component Analysis Of Gene-Environment Interactions<br/>Taesung Park</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_178" style = "color: black;">Wavelet-Based Power Transformation Of Non-Gaussian Long Memory Time Series<br/>Kyungduk Ko</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_166" style = "color: black;">Cross Covariance Estimation For Integration Of Multi-Omics Data<br/>Hyungwon Choi</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_137" style = "color: black;">Relationships Between Linguistic Characteristics And The Use Of Māori Loanwords In New Zealand English.<br/>Steven Miller</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_005" style = "color: black;">Transfer Regression And Predictive Distributions<br/>Jinfang Wang</a></td>
</tr>
<tr>
<td class = "time">1430</td>
<td class = "contributed"><a href="Wednesday.html#talk_136" style = "color: black;">An Overview Of The Correspondence Analysis Family<br/>Eric Beh</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_173" style = "color: black;">Testing For Genetic Associations In Arbitrarily Structured Populations<br/>Minsun Song</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_179" style = "color: black;">Threshold Determination For The Meteorological Data Quality Control In Korea<br/>Yung-Seop Lee</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_167" style = "color: black;">Regularized Noise-Reduction Methodology For High-Dimensional Data<br/>Kazuyoshi Yata</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_117" style = "color: black;">Computation Of Influence Functions For Robust Statistics<br/>Maheswaran Rohan</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_026" style = "color: black;">Adaptive Model Averaging In High-Dimensional Linear Regression<br/>Tzu-Chang Forrest Cheng</a></td>
</tr>
<tr>
<td class = "time">1450</td>
<td class = "contributed"><a href="Wednesday.html#talk_145" style = "color: black;">Model-Based Clustering For Multivariate Categorical Data With Dimension Reduction<br/>Michio Yamamoto</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_186" style = "color: black;">Phylogenetic Tree-Based Microbiome Association Test<br/>Sungho Won</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_181" style = "color: black;">Fitting Additive Hazards Model Using Calibrated Weights For Case-Cohort Data<br/>Sangwook Kang</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_168" style = "color: black;">Selecting The Number Of Principal Components<br/>Yunjin Choi</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_083" style = "color: black;">Rolling Survival Extrapolation Algorithm For Estimating Life Years Lost Among Subjects Exposed To Long-Term Air Pollution<br/>Jing-Shiang Hwang</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_153" style = "color: black;">Enhancing The Flexibility Of Regression Modeling By Liquid Association<br/>Ker-Chau Li</a></td>
</tr>
<tr>
<td class = "time">1510</td>
<td class = "contributed"><a href="Wednesday.html#talk_058" style = "color: black;">Clusterwise Low-Rank Correlation Analysis Based On Majorization<br/>Kensuke Tanioka</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Wednesday.html#talk_183" style = "color: black;">Bayesian Analysis For Fitting Zero-Inflated Count Data With Data Augmentation<br/>Beomseuk Hwang</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_172" style = "color: black;">Towards A Sparse, Scalable, And Stably Positive Definite (Inverse) Covariance Estimator<br/>Joong-Ho Won</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_195" style = "color: black;">Tick-By-Tick Effect On The Inference Of Ultra-High Frequency Data<br/>Zhi Liu</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_154" style = "color: black;">High Mortality Predictions With Lines Or Curves Fitted To Over-Dispersed Exposure-Mortality Data<br/>John Maindonald</a></td>
</tr>
<tr>
<td class = "time">1530</td>
<td class = "mealbreak" colspan = "6">Afternoon tea (30 minutes)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 1(260-005)</td>
</tr>
<tr>
<td class = "time">1600</td>
<td class = "contributed"><a href="Wednesday.html#talk_008" style = "color: black;">Lattice Polytope Samplers<br/>Martin Hazelton</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_160" style = "color: black;">Statistical Modelling And Analysis Of Cosmic Microwave Background Data<br/>Andriy Olenko</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_090" style = "color: black;">Measure Of Departure From Marginal Average Point-Symmetry For Two-Way Contingency Tables With Ordered Categories<br/>Kiyotaka Iki</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_123" style = "color: black;">Sparse Estimates From Dense Precision Matrix Posteriors<br/>Beatrix Jones</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_068" style = "color: black;">Dimension Reduction Strategies For Modeling Bi-Clustered High Dimensional Data<br/>Michael Van Supranes</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1620</td>
<td class = "contributed"><a href="Wednesday.html#talk_126" style = "color: black;">Computing Entropies With Nested Sampling<br/>Brendon Brewer</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_163" style = "color: black;">Spline-Based Drift Models For High Temperature Operating Life Tests<br/>Thomas Nowak</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_114" style = "color: black;">A New Approach To Distribution Free Tests In Contingency Tables<br/>Thuong Nguyen</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_202" style = "color: black;">A Bayesian Inference For Time Series Via Copula-Based Markov Chain Models<br/>Li-Hsien Sun</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_104" style = "color: black;">Modified Gene Shaving Algorithm - A Dimension Reduction And Clustering Method<br/>Donna Mae Santos</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1640</td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Wednesday.html#talk_196" style = "color: black;">A Simple Method To Construct Confidence Bands In Functional Linear Regression<br/>Kengo Kato</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_129" style = "color: black;">Separation Of Symmetry For Square Contingency Tables With Ordinal Categories<br/>Kouji Tahata</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;">Scalable Kernel-Based Variable Selection With Sparsistency<br/>Junhui Wang</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_107" style = "color: black;">Testing For Presence Of Clustering Effect In Multilevel Model With High-Dimensional Predictors<br/>Frances Claire San Juan</a></td>
<td class = "contributed"><a href="Wednesday.html#talk_NA" style = "color: black;"></a></td>
</tr>
</tbody>
</table>
</div>
## Thursday {#Thursday-tbl .unnumbered}
<div style = "overflow-x:auto;">
<table style = "width: 4000px;">
<thead>
<tr>
<th class = "time">Time</th>
<th class = "day">Thursday 14<sup>th</sup></th>
</tr>
</thead>
<tbody>
<tr>
<td class = "time">900</td>
<td class = "housekeeping" colspan = "6">Housekeeping</td>
</tr>
<tr>
<td class = "time">910</td>
<td class = "keynote" colspan = "6"><a href="Thursday.html#talk_199" style = "color: white;">ALTREP: Alternate Representations Of Basic R Objects<br/>Luke Tierney, University of Iowa, USA<br/>098 Lecture Theatre (260-098)</a></td>
</tr>
<tr>
<td class = "time">1000</td>
<td class = "mealbreak" colspan = "6">Morning Tea (30 minutes)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1030</td>
<td class = "contributed"><a href="Thursday.html#talk_133" style = "color: black;">Penalized Vector Generalized Additive Models<br/>Thomas Yee</a></td>
<td class = "contributed"><a href="Thursday.html#talk_069" style = "color: black;">A Package For Multiple Precision Floating-Point Computation On R<br/>Junji Nakano</a></td>
<td class = "contributed"><a href="Thursday.html#talk_043" style = "color: black;">Dissimilarities Between Groups Of Data<br/>Nobuo Shimizu</a></td>
<td class = "contributed"><a href="Thursday.html#talk_042" style = "color: black;">Comparison Of Tests Of Mean Difference In Longitudinal Data Based On Block Resampling Methods<br/>Hirohito Sakurai</a></td>
<td class = "contributed"><a href="Thursday.html#talk_099" style = "color: black;">SSREM: A Summary-Statistics-Based Random Effect Model To Estimating Heritability, Co-Heritability And Effect Sizes In GWAS Data Analysis<br/>Jin Liu</a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1050</td>
<td class = "contributed"><a href="Thursday.html#talk_106" style = "color: black;">Consistency Of Linear Mixed-Effects Model Selection With Inconsistent Covariance Parameter Estimators<br/>Chihhao Chang</a></td>
<td class = "contributed"><a href="Thursday.html#talk_051" style = "color: black;">An Incomplete-Data Fisher Scoring With An Acceleration Method<br/>Keiji Takai</a></td>
<td class = "contributed"><a href="Thursday.html#talk_089" style = "color: black;">Interactive Visualization Of Aggregated Symbolic Data<br/>Yoshikazu Yamamoto</a></td>
<td class = "contributed"><a href="Thursday.html#talk_097" style = "color: black;">Analysis Of Spatial Data With A Gaussian Mixture Markov Random Field Model<br/>Wataru Sakamoto</a></td>
<td class = "contributed"><a href="Thursday.html#talk_120" style = "color: black;">Forward Selection In Regression Models Based On Robust Estimation<br/>Shan Luo</a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1110</td>
<td class = "contributed"><a href="Thursday.html#talk_048" style = "color: black;">Selecting Generalised Linear Models Under Inequality Constraints<br/>Daniel Gerhard</a></td>
<td class = "contributed"><a href="Thursday.html#talk_057" style = "color: black;">Improvement Of Computation For Nonlinear Multivariate Methods<br/>Yuichi Mori</a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Thursday.html#talk_121" style = "color: black;">Feature Selection In High-Dimensional Models With Complex Block Structures<br/>Zehua Chen</a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1130</td>
<td class = "contributed"><a href="Thursday.html#talk_165" style = "color: black;">Statistical Generalized Derivative Applied To The Profile Likelihood Estimation In A Mixture Of Semiparametric Models<br/>Yuichi Hirose</a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
<td class = "contributed"><a href="Thursday.html#talk_NA" style = "color: black;"></a></td>
</tr>
<tr>
<td class = "time">1200</td>
<td class = "confclose" colspan = "6">Closing Ceremony<br/>098 Lecture Theatre (260-098)</td>
</tr>
<tr>
<td class = "time">1220</td>
<td class = "mealbreak" colspan = "6">Lunch (1 hour 10 minutes)</td>
</tr>
</tbody>
</table>
</div>
