# Index by Submission Number {#indexbysubmission .unnumbered}
<table>
<thead>
<tr>
<th style = "width: 10%;">Sub.</th>
<th style = "width: 90%;">Title</th>
</tr>
</thead>
<tbody>
<tr><td><a href = "Monday.html#talk_002">002</a></td><td><a href = "Monday.html#talk_002">Effect Of Area Level Deprivation On Body Mass Index: Analysis Of NZ Health Surveys</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_003">003</a></td><td><a href = "Wednesday.html#talk_003">Online Learning For Bayesian Nonparametrics: Weakly Conjugate Approximation</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_004">004</a></td><td><a href = "Wednesday.html#talk_004">The Joint Models For Nonlinear Longitudinal And Time-To-Event Data Using Penalized Splines: A Bayesian Approach</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_005">005</a></td><td><a href = "Wednesday.html#talk_005">Transfer Regression And Predictive Distributions</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_006">006</a></td><td><a href = "Wednesday.html#talk_006">Sparse Common Component Analysis</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_007">007</a></td><td><a href = "Wednesday.html#talk_007">Specification Of GARCH Model Under Asymmetric Error Innovations</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_008">008</a></td><td><a href = "Wednesday.html#talk_008">Lattice Polytope Samplers</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_009">009</a></td><td><a href = "Wednesday.html#talk_009">Promoting Your R Package</a></td></tr>
<tr><td><a href = "Monday.html#talk_010">010</a></td><td><a href = "Monday.html#talk_010">Incorporating Genetic Networks Into Case-Control Association Studies With High-Dimensional DNA Methylation Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_011">011</a></td><td><a href = "Wednesday.html#talk_011">Presenting Flexi, A Statistical Program For Fitting Variance Models</a></td></tr>
<tr><td><a href = "Monday.html#talk_012">012</a></td><td><a href = "Monday.html#talk_012">Calendar-Based Graphics For Visualising People's Daily Schedules</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_013">013</a></td><td><a href = "Tuesday.html#talk_013">Estimation And Prediction For A Distribution With Bathtub Shape Under Progressive First Failure Censoring</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_014">014</a></td><td><a href = "Tuesday.html#talk_014">Bayesian Optimum Warranty Length Under Type-II Unified Hybrid Censoring Scheme</a></td></tr>
<tr><td><a href = "Monday.html#talk_015">015</a></td><td><a href = "Monday.html#talk_015">Adaptive Model Checking For Functional Single-Index Models</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_016">016</a></td><td><a href = "Tuesday.html#talk_016">An EWMA Chart For Monitoring Covariance Matrix Based On Dissimilarity Index</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_017">017</a></td><td><a href = "Tuesday.html#talk_017">Analysis Of Multivariate Binary Longitudinal Data: Metabolic Syndrome During Menopausal Transition</a></td></tr>
<tr><td><a href = "Monday.html#talk_018">018</a></td><td><a href = "Monday.html#talk_018">Test For Genomic Imprinting Effects On The X Chromosome</a></td></tr>
<tr><td><a href = "Monday.html#talk_019">019</a></td><td><a href = "Monday.html#talk_019">A Unified Regularized Group PLS Algorithm Scalable To Big Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_020">020</a></td><td><a href = "Monday.html#talk_020">Bayesian Analyses Of Non-Homogeneous Gaussian Hidden Markov Models</a></td></tr>
<tr><td><a href = "Monday.html#talk_021">021</a></td><td><a href = "Monday.html#talk_021">Clustering Using Nonparametric Mixtures And Mode Identification</a></td></tr>
<tr><td><a href = "Monday.html#talk_022">022</a></td><td><a href = "Monday.html#talk_022">Robust Principal Expectile Component Analysis</a></td></tr>
<tr><td><a href = "Monday.html#talk_023">023</a></td><td><a href = "Monday.html#talk_023">Estimation Of A High-Dimensional Covariance Matrix</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_024">024</a></td><td><a href = "Tuesday.html#talk_024">Identifying Clusters Of Patients With Diabetes Using A Markov Birth-Death Process</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_025">025</a></td><td><a href = "Tuesday.html#talk_025">R&amp;D Policy Regimes In France: New Evidence From A Spatio-Temporal Analysis</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_026">026</a></td><td><a href = "Wednesday.html#talk_026">Adaptive Model Averaging In High-Dimensional Linear Regression</a></td></tr>
<tr><td><a href = "Monday.html#talk_027">027</a></td><td><a href = "Monday.html#talk_027">Fluctuation Reduction Of Value-At-Risk Estimation And Its Applications</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_028">028</a></td><td><a href = "Tuesday.html#talk_028">Spatial Surveillance With Scan Statistics By Controlling The False Discovery Rate</a></td></tr>
<tr><td><a href = "Monday.html#talk_029">029</a></td><td><a href = "Monday.html#talk_029">Genetic Map Estimation Using Hidden Markov Models In The Presence Of Partially Observed Information</a></td></tr>
<tr><td><a href = "Monday.html#talk_030">030</a></td><td><a href = "Monday.html#talk_030">Estimation Of A Semiparametric Spatiotemporal Models With Mixed Frequency</a></td></tr>
<tr><td><a href = "Monday.html#talk_031">031</a></td><td><a href = "Monday.html#talk_031">Vector Generalized Linear Time Series Models</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_032">032</a></td><td><a href = "Wednesday.html#talk_032">gridSVG: Then And Now</a></td></tr>
<tr><td><a href = "Monday.html#talk_033">033</a></td><td><a href = "Monday.html#talk_033">Evaluation Of Spatial Cluster Detection Method Based On All Geographical Linkage Patterns</a></td></tr>
<tr><td><a href = "Monday.html#talk_034">034</a></td><td><a href = "Monday.html#talk_034">On Optimal Group Testing Designs: Prevalence Estimation, Cost Considerations, And Dilution Effects</a></td></tr>
<tr><td><a href = "Monday.html#talk_035">035</a></td><td><a href = "Monday.html#talk_035">Evidence Of Climate Change From Nonparametric Change-Point Analysis</a></td></tr>
<tr><td><a href = "Monday.html#talk_036">036</a></td><td><a href = "Monday.html#talk_036">Nonparametric Test For Volatility In Clustered Multiple Time Series</a></td></tr>
<tr><td><a href = "Monday.html#talk_037">037</a></td><td><a href = "Monday.html#talk_037">Bayesian Curve Fitting For Discontinuous Function Using Overcomplete Representation With Multiple Kernels</a></td></tr>
<tr><td><a href = "Monday.html#talk_038">038</a></td><td><a href = "Monday.html#talk_038">Variable Selection Algorithms</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_039">039</a></td><td><a href = "Tuesday.html#talk_039">Towards An Informal Test For Goodness-Of-Fit</a></td></tr>
<tr><td><a href = "Monday.html#talk_040">040</a></td><td><a href = "Monday.html#talk_040">Genetic Approach And Statistical Approach For Association Study On DNA Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_041">041</a></td><td><a href = "Monday.html#talk_041">The Use Of Bayesian Networks In Grape Yield Prediction</a></td></tr>
<tr><td><a href = "Thursday.html#talk_042">042</a></td><td><a href = "Thursday.html#talk_042">Comparison Of Tests Of Mean Difference In Longitudinal Data Based On Block Resampling Methods</a></td></tr>
<tr><td><a href = "Thursday.html#talk_043">043</a></td><td><a href = "Thursday.html#talk_043">Dissimilarities Between Groups Of Data</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_044">044</a></td><td><a href = "Tuesday.html#talk_044">The Uncomfortable Entrepreneurs: Bad Working Conditions And Entrepreneurial Commitment</a></td></tr>
<tr><td><a href = "Monday.html#talk_045">045</a></td><td><a href = "Monday.html#talk_045">Mixed Models For Complex Survey Data</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_046">046</a></td><td><a href = "Tuesday.html#talk_046">Intensity Estimation Of Spatial Point Processes Based On Area-Aggregated Data</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_047">047</a></td><td><a href = "Tuesday.html#talk_047">How Does The Textile Set Describe Geometric Structures Of Data?</a></td></tr>
<tr><td><a href = "Thursday.html#talk_048">048</a></td><td><a href = "Thursday.html#talk_048">Selecting Generalised Linear Models Under Inequality Constraints</a></td></tr>
<tr><td><a href = "Monday.html#talk_049">049</a></td><td><a href = "Monday.html#talk_049">Bayesian Structure Selection For Vector Autoregression Model</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_050">050</a></td><td><a href = "Wednesday.html#talk_050">Improving The Production Cycle At Stats NZ With RStudio</a></td></tr>
<tr><td><a href = "Thursday.html#talk_051">051</a></td><td><a href = "Thursday.html#talk_051">An Incomplete-Data Fisher Scoring With An Acceleration Method</a></td></tr>
<tr><td><a href = "Monday.html#talk_052">052</a></td><td><a href = "Monday.html#talk_052">Smooth Nonparametric Regression Under Shape Restrictions</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_053">053</a></td><td><a href = "Wednesday.html#talk_053">R – A Powerful Analysis Tool To Improve Official Statistics In Romania</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_054">054</a></td><td><a href = "Wednesday.html#talk_054">Statistical Disclosure Control With R: Traditional Methods And Synthetic Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_055">055</a></td><td><a href = "Monday.html#talk_055">Innovative Bayesian Estimation In The von Mises Distribution</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_056">056</a></td><td><a href = "Wednesday.html#talk_056">Cluster-Wise Regression Models Combined By A Quasi-Linear Function</a></td></tr>
<tr><td><a href = "Thursday.html#talk_057">057</a></td><td><a href = "Thursday.html#talk_057">Improvement Of Computation For Nonlinear Multivariate Methods</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_058">058</a></td><td><a href = "Wednesday.html#talk_058">Clusterwise Low-Rank Correlation Analysis Based On Majorization</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_059">059</a></td><td><a href = "Wednesday.html#talk_059">Empirical Comparison Of Some Algorithms For Automatic Univariate ARMA Modeling Using RcmdrPlugin.SPSS</a></td></tr>
<tr><td><a href = "Monday.html#talk_060">060</a></td><td><a href = "Monday.html#talk_060">Robustness Of Temperature Reconstruction For Past 500 Years</a></td></tr>
<tr><td><a href = "Monday.html#talk_061">061</a></td><td><a href = "Monday.html#talk_061">Estimation Of Animal Density From Acoustic Detections</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_062">062</a></td><td><a href = "Wednesday.html#talk_062">Random Search Global Optimization Using Random Forests</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_063">063</a></td><td><a href = "Wednesday.html#talk_063">A Max-Type Multivariate Two-Sample Baumgartner Statistic</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_064">064</a></td><td><a href = "Wednesday.html#talk_064">Performance Of Bayesian Credible Interval For Binomial Proportion Using Logit Transformation</a></td></tr>
<tr><td><a href = "Monday.html#talk_065">065</a></td><td><a href = "Monday.html#talk_065">Semiparametric Mixed Analysis Of Covariance Model</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_066">066</a></td><td><a href = "Wednesday.html#talk_066">Bringing Multimix From Fortran To R</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_067">067</a></td><td><a href = "Tuesday.html#talk_067">Geographically Weighted Principal Component Analysis For Spatio-Temporal Statistical Dataset</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_068">068</a></td><td><a href = "Wednesday.html#talk_068">Dimension Reduction Strategies For Modeling Bi-Clustered High Dimensional Data</a></td></tr>
<tr><td><a href = "Thursday.html#talk_069">069</a></td><td><a href = "Thursday.html#talk_069">A Package For Multiple Precision Floating-Point Computation On R</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_071">071</a></td><td><a href = "Wednesday.html#talk_071">Simultaneous Test For Mean Vectors And Covariance Matrices In High-Dimensional Settings</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_072">072</a></td><td><a href = "Tuesday.html#talk_072">Detecting Change-Points In The Stress-Strength Reliability P(X&LT;Y)</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_073">073</a></td><td><a href = "Tuesday.html#talk_073">Two Stage Approach To Data-Driven Subgroup Identification In Clinical Trials</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_074">074</a></td><td><a href = "Tuesday.html#talk_074">Adjusted Adaptive Index Model For Binary Response</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_075">075</a></td><td><a href = "Wednesday.html#talk_075">Dimension Reduction For Classification Of High-Dimensional Data By Stepwise SVM</a></td></tr>
<tr><td><a href = "Monday.html#talk_076">076</a></td><td><a href = "Monday.html#talk_076">A Simple Method For Grouping Patients Based On Historical Doses</a></td></tr>
<tr><td><a href = "Monday.html#talk_077">077</a></td><td><a href = "Monday.html#talk_077">Real-Time Transit Network Modelling For Improved Arrival Time Predictions</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_078">078</a></td><td><a href = "Tuesday.html#talk_078">Ranking Potential Shoplifters In Real Time</a></td></tr>
<tr><td><a href = "Monday.html#talk_079">079</a></td><td><a href = "Monday.html#talk_079">Canonical Covariance Analysis For Mixed Numerical And Categorical Three-Way Three-Mode Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_080">080</a></td><td><a href = "Monday.html#talk_080">Bayesian Survival Analysis Of Batsmen In Test Cricket</a></td></tr>
<tr><td><a href = "Monday.html#talk_081">081</a></td><td><a href = "Monday.html#talk_081">Flight To Relative Safety: Learning From A No-Arbitrage Network Of Yield Curves Model Of The Euro Area</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_083">083</a></td><td><a href = "Wednesday.html#talk_083">Rolling Survival Extrapolation Algorithm For Estimating Life Years Lost Among Subjects Exposed To Long-Term Air Pollution</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_084">084</a></td><td><a href = "Tuesday.html#talk_084">Analysing Scientific Collaborations Of New Zealand Institutions Using Scopus Bibliometric Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_085">085</a></td><td><a href = "Monday.html#talk_085">Genetic Predictors Underlying Long-Term Cognitive Recovery Following Mild Traumatic Brain Injury</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_086">086</a></td><td><a href = "Tuesday.html#talk_086">Correlated Defaults With A Distance To Default</a></td></tr>
<tr><td><a href = "Monday.html#talk_087">087</a></td><td><a href = "Monday.html#talk_087">Symbolic Data Analytical Approach To Unauthorized-Access Logs</a></td></tr>
<tr><td><a href = "Monday.html#talk_088">088</a></td><td><a href = "Monday.html#talk_088">Bayesian Static Parameter Inference For Partially Observed Stochastic Systems</a></td></tr>
<tr><td><a href = "Thursday.html#talk_089">089</a></td><td><a href = "Thursday.html#talk_089">Interactive Visualization Of Aggregated Symbolic Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_090">090</a></td><td><a href = "Wednesday.html#talk_090">Measure Of Departure From Marginal Average Point-Symmetry For Two-Way Contingency Tables With Ordered Categories</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_091">091</a></td><td><a href = "Tuesday.html#talk_091">Optimizing Junior Rugby Weight Limits</a></td></tr>
<tr><td><a href = "Monday.html#talk_092">092</a></td><td><a href = "Monday.html#talk_092">BIG-SIR A Sliced Inverse Regression Approach For Massive Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_093">093</a></td><td><a href = "Monday.html#talk_093">Local Canonical Correlation Analysis For Multimodal Labeled Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_094">094</a></td><td><a href = "Monday.html#talk_094">Estimating Causal Structures For Continuous And Discrete Variables</a></td></tr>
<tr><td><a href = "Monday.html#talk_095">095</a></td><td><a href = "Monday.html#talk_095">Meta-Analysis With Symbolic Data Analysis And Its Application For Clinical Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_096">096</a></td><td><a href = "Wednesday.html#talk_096">Deep Learning High-Dimensional Covariance Matrices</a></td></tr>
<tr><td><a href = "Thursday.html#talk_097">097</a></td><td><a href = "Thursday.html#talk_097">Analysis Of Spatial Data With A Gaussian Mixture Markov Random Field Model</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_098">098</a></td><td><a href = "Wednesday.html#talk_098">Imputation Of The 2016 Economic Census For Business Activity In Japan</a></td></tr>
<tr><td><a href = "Thursday.html#talk_099">099</a></td><td><a href = "Thursday.html#talk_099">SSREM: A Summary-Statistics-Based Random Effect Model To Estimating Heritability, Co-Heritability And Effect Sizes In GWAS Data Analysis</a></td></tr>
<tr><td><a href = "Monday.html#talk_100">100</a></td><td><a href = "Monday.html#talk_100">A Practitioners Guide To Deep Learning For Predictive Analytics On Structured Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_101">101</a></td><td><a href = "Monday.html#talk_101">Pattern Prediction For Time Series Data With Change Points</a></td></tr>
<tr><td><a href = "Monday.html#talk_102">102</a></td><td><a href = "Monday.html#talk_102">Regression With Random Effects For Analysing Correlated Survival Data: Application To Disease Recurrences</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_103">103</a></td><td><a href = "Tuesday.html#talk_103">Comparison Of Exact And Approximate Testing Procedures In Clinical Trials With Multiple Binary Endpoints</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_104">104</a></td><td><a href = "Wednesday.html#talk_104">Modified Gene Shaving Algorithm - A Dimension REduction And Clustering Method</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_105">105</a></td><td><a href = "Wednesday.html#talk_105">Applying Active Learning Procedure To Drug Consumption Data</a></td></tr>
<tr><td><a href = "Thursday.html#talk_106">106</a></td><td><a href = "Thursday.html#talk_106">Consistency Of Linear Mixed-Effects Model Selection With Inconsistent Covariance Parameter Estimators</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_107">107</a></td><td><a href = "Wednesday.html#talk_107">Testing For Presence Of Clustering Effect In Multilevel Model With High-Dimensional Predictors</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_108">108</a></td><td><a href = "Wednesday.html#talk_108">High Dimensional Asymptotics For The Naive Canonical Correlation Coefficient</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_109">109</a></td><td><a href = "Tuesday.html#talk_109">Factors Influencing On Growth Of Garments Industry In Bangladesh</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_111">111</a></td><td><a href = "Tuesday.html#talk_111">New Zealand Crime And Victims Survey: Filling The Knowledge Gap</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_112">112</a></td><td><a href = "Wednesday.html#talk_112">Analysis Of Official Microdata Using Secure Statistical Computation System</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_113">113</a></td><td><a href = "Tuesday.html#talk_113">Statistical Models For The Source Attribution Of Zoonotic Diseases: A Study Of Campylobacteriosis</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_114">114</a></td><td><a href = "Wednesday.html#talk_114">A New Approach To Distribution Free Tests In Contingency Tables</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_115">115</a></td><td><a href = "Tuesday.html#talk_115">Bayesian Inference For Population Attributable Measures</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_116">116</a></td><td><a href = "Tuesday.html#talk_116">Dimensionality Reduction Of Multivariate Data For Bayesian Analysis</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_117">117</a></td><td><a href = "Wednesday.html#talk_117">Computation Of Influence Functions For Robust Statistics</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_118">118</a></td><td><a href = "Tuesday.html#talk_118">Analysis Of A Brief Telephone Intervention For Problem Gambling And Examining The Impact On Co-Existing Depression?</a></td></tr>
<tr><td><a href = "Thursday.html#talk_120">120</a></td><td><a href = "Thursday.html#talk_120">Forward Selection In Regression Models Based On Robust Estimation</a></td></tr>
<tr><td><a href = "Thursday.html#talk_121">121</a></td><td><a href = "Thursday.html#talk_121">Feature Selection In High-Dimensional Models With Complex Block Structures</a></td></tr>
<tr><td><a href = "Monday.html#talk_122">122</a></td><td><a href = "Monday.html#talk_122">IGESS: A Statistical Approach To Integrating Individual Level Genotype Data And Summary Statistics In Genome Wide Association Studies</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_123">123</a></td><td><a href = "Wednesday.html#talk_123">Sparse Estimates From Dense Precision Matrix Posteriors</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_124">124</a></td><td><a href = "Tuesday.html#talk_124">Whitebait In All Its Varieties: One Fish, Two Fish, Three, Four, Five Fish.</a></td></tr>
<tr><td><a href = "Monday.html#talk_125">125</a></td><td><a href = "Monday.html#talk_125">Adaptive False Discovery Rate Regression With Application In Integrative Analysis Of Large-Scale Genomic Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_126">126</a></td><td><a href = "Wednesday.html#talk_126">Computing Entropies With Nested Sampling</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_127">127</a></td><td><a href = "Tuesday.html#talk_127">Missing Data In Randomised Control Trials: Stepped Multiple Imputation</a></td></tr>
<tr><td><a href = "Monday.html#talk_128">128</a></td><td><a href = "Monday.html#talk_128">Author Name Identification For Evaluating Research Performance Of Institutes</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_129">129</a></td><td><a href = "Wednesday.html#talk_129">Separation Of Symmetry For Square Contingency Tables With Ordinal Categories</a></td></tr>
<tr><td><a href = "Monday.html#talk_130">130</a></td><td><a href = "Monday.html#talk_130">Elastic-Band Transform: A New Approach To Multiscale Visualization</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_132">132</a></td><td><a href = "Tuesday.html#talk_132">Bayesian Continuous Space-Time Model Of Burglaries</a></td></tr>
<tr><td><a href = "Thursday.html#talk_133">133</a></td><td><a href = "Thursday.html#talk_133">Penalized Vector Generalized Additive Models</a></td></tr>
<tr><td><a href = "Monday.html#talk_134">134</a></td><td><a href = "Monday.html#talk_134">Scoring Rules For Prediction And Classification Challenges</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_135">135</a></td><td><a href = "Tuesday.html#talk_135">Breeding Value Estimation In Partially-Genotyped Populations</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_136">136</a></td><td><a href = "Wednesday.html#talk_136">An Overview Of The Correspondence Analysis Family</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_137">137</a></td><td><a href = "Wednesday.html#talk_137">Relationships Between Linguistic Characteristics And The Use Of Māori Loanwords In New Zealand English.</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_138">138</a></td><td><a href = "Tuesday.html#talk_138">Including Covariate Estimation Error When Predicting Species Distributions: A Simulation Exercise Using Template Model Builder</a></td></tr>
<tr><td><a href = "Monday.html#talk_139">139</a></td><td><a href = "Monday.html#talk_139">Nonparametric Causal Inference By The Kernel Method</a></td></tr>
<tr><td><a href = "Monday.html#talk_140">140</a></td><td><a href = "Monday.html#talk_140">Sparse Group-Subgroup Partial Least Squares With Application To Genomic Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_141">141</a></td><td><a href = "Wednesday.html#talk_141">R In Industry – Application On Pipe Renewal Planning</a></td></tr>
<tr><td><a href = "Monday.html#talk_142">142</a></td><td><a href = "Monday.html#talk_142">Covariate Discretisation On Big Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_143">143</a></td><td><a href = "Wednesday.html#talk_143">R Package For New Two-Stage Methods In Forecasting Time Series With Multiple Seasonality</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_144">144</a></td><td><a href = "Tuesday.html#talk_144">Spatial Scan Statistics For Matched Case-Control Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_145">145</a></td><td><a href = "Wednesday.html#talk_145">Model-Based Clustering For Multivariate Categorical Data With Dimension Reduction</a></td></tr>
<tr><td><a href = "Monday.html#talk_146">146</a></td><td><a href = "Monday.html#talk_146">Talk Data To Me</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_147">147</a></td><td><a href = "Tuesday.html#talk_147">An Information Criterion For Prediction With Auxiliary Variables Under Covariate Shift</a></td></tr>
<tr><td><a href = "Monday.html#talk_148">148</a></td><td><a href = "Monday.html#talk_148">LSMM: A Statistical Approach To Integrating Functional Annotations With Genome-Wide Association Studies</a></td></tr>
<tr><td><a href = "Monday.html#talk_149">149</a></td><td><a href = "Monday.html#talk_149">Visualization And Statistical Modeling Of Financial Big Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_150">150</a></td><td><a href = "Monday.html#talk_150">Modeling Of Document Abstraction Using Association Rule Based Characterization</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_151">151</a></td><td><a href = "Tuesday.html#talk_151">BIVAS: A Scalable Bayesian Method For Bi-Level Variable Selection</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_153">153</a></td><td><a href = "Wednesday.html#talk_153">Enhancing The Flexibility Of Regression Modeling By Liquid Association</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_154">154</a></td><td><a href = "Wednesday.html#talk_154">High Mortality Predictions With Lines Or Curves Fitted To Over-Dispersed Exposure-Mortality Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_155">155</a></td><td><a href = "Monday.html#talk_155">A Computational Tool For Detecting Copy Number Variations From Whole Genome And Targeted Exome Sequencing</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_156">156</a></td><td><a href = "Tuesday.html#talk_156">Modelling The Distribution Of Lifetime Using Compound Time-Homogenous Poisson Process</a></td></tr>
<tr><td><a href = "Monday.html#talk_157">157</a></td><td><a href = "Monday.html#talk_157">An Advanced Approach For Time Series Forecasting Using Deep Learning</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_158">158</a></td><td><a href = "Wednesday.html#talk_158">A Smoothing Filter Modelling Approach For Time Series</a></td></tr>
<tr><td><a href = "Monday.html#talk_159">159</a></td><td><a href = "Monday.html#talk_159">Structure Of Members In The Organization To Induce Innovation: Quantitatively Analyze The Capability Of The Organization</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_160">160</a></td><td><a href = "Wednesday.html#talk_160">Statistical Modelling And Analysis Of Cosmic Microwave Background Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_161">161</a></td><td><a href = "Monday.html#talk_161">Joint Analysis Of Individual Level Genotype Data And Summary Statistics By Leveraging Pleiotropy</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_162">162</a></td><td><a href = "Tuesday.html#talk_162">Adjusting For Linkage Bias In The Analysis Of Record-Linked Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_163">163</a></td><td><a href = "Wednesday.html#talk_163">Spline-Based Drift Models For High Temperature Operating Life Tests</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_164">164</a></td><td><a href = "Tuesday.html#talk_164">Tolerance Limits For The Reliability Of Semiconductor Devices Using Longitudinal Data</a></td></tr>
<tr><td><a href = "Thursday.html#talk_165">165</a></td><td><a href = "Thursday.html#talk_165">Statistical Generalized Derivative Applied To The Profile Likelihood Estimation In A Mixture Of Semiparametric Models</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_166">166</a></td><td><a href = "Wednesday.html#talk_166">Cross Covariance Estimation For Integration Of Multi-Omics Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_167">167</a></td><td><a href = "Wednesday.html#talk_167">Regularized Noise-Reduction Methodology For High-Dimensional Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_168">168</a></td><td><a href = "Wednesday.html#talk_168">Selecting The Number Of Principal Components</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_169">169</a></td><td><a href = "Tuesday.html#talk_169">Clustering Of Curves On A Spatial Domain Using A Bayesian Partitioning Model</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_170">170</a></td><td><a href = "Tuesday.html#talk_170">Family Structure And Academic Achievements Of High School Students In Tonga</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_171">171</a></td><td><a href = "Wednesday.html#talk_171">Hierarchical Structural Component Analysis Of Gene-Environment Interactions</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_172">172</a></td><td><a href = "Wednesday.html#talk_172">Towards A Sparse, Scalable, And Stably Positive Definite (Inverse) Covariance Estimator</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_173">173</a></td><td><a href = "Wednesday.html#talk_173">Testing For Genetic Associations In Arbitrarily Structured Populations</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_174">174</a></td><td><a href = "Tuesday.html#talk_174">Bayesian Temporal Density Estimation Using Autoregressive Species Sampling Models</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_175">175</a></td><td><a href = "Tuesday.html#talk_175">Prior-Based Bayesian Information Criterion</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_176">176</a></td><td><a href = "Tuesday.html#talk_176">Bayesian Semiparametric Hierarchical Models For Longitudinal Data Analysis With Application To Dose-Response Studies</a></td></tr>
<tr><td><a href = "Monday.html#talk_177">177</a></td><td><a href = "Monday.html#talk_177">Mobile Learning In Teaching Bioinformatics For Medical Doctors</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_178">178</a></td><td><a href = "Wednesday.html#talk_178">Wavelet-Based Power Transformation Of Non-Gaussian Long Memory Time Series</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_179">179</a></td><td><a href = "Wednesday.html#talk_179">Threshold Determination For The Meteorological Data Quality Control In Korea</a></td></tr>
<tr><td><a href = "Monday.html#talk_180">180</a></td><td><a href = "Monday.html#talk_180">Meta-Analytic Principal Component Analysis In Integrative Omics Application</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_181">181</a></td><td><a href = "Wednesday.html#talk_181">Fitting Additive Hazards Model Using Calibrated Weights For Case-Cohort Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_182">182</a></td><td><a href = "Monday.html#talk_182">Three-Dimensional Data Visualization Education With Virtual Reality</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_183">183</a></td><td><a href = "Wednesday.html#talk_183">Bayesian Analysis For Fitting Zero-Inflated Count Data With Data Augmentation</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_184">184</a></td><td><a href = "Tuesday.html#talk_184">Inverse Regression For Multivariate Functional Data</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_185">185</a></td><td><a href = "Tuesday.html#talk_185">Multiple Function-On-Function Linear Regression With Application To Weather Forecast Calibration</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_186">186</a></td><td><a href = "Wednesday.html#talk_186">Phylogenetic Tree-Based Microbiome Association Test</a></td></tr>
<tr><td><a href = "Monday.html#talk_187">187</a></td><td><a href = "Monday.html#talk_187">A Study Of The Influence Of Articles In The Large-Scale Citation Network</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_188">188</a></td><td><a href = "Wednesday.html#talk_188">Probabilistic Outlier Detection And Visualization Of Smart Meter Data</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_189">189</a></td><td><a href = "Tuesday.html#talk_189">Model-Checking For Regressions: A Local Smoothing-Based Global Smoothing Test</a></td></tr>
<tr><td><a href = "Monday.html#talk_190">190</a></td><td><a href = "Monday.html#talk_190">Clustering Of Research Subject Based On Stochastic Block Model</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_191">191</a></td><td><a href = "Tuesday.html#talk_191">Latent Variable Models And Multivariate Binomial Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_192">192</a></td><td><a href = "Monday.html#talk_192">My Knee Still Hurts; The Statistical Pathway To The Development Of A Clinical Decision Aid</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_193">193</a></td><td><a href = "Tuesday.html#talk_193">Asking About Sex In General Health Surveys: Comparing The Methods And Findings Of The 2010 Health Survey For England With Those Of The Third National Survey Of Sexual Attitudes And Lifestyles</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_194">194</a></td><td><a href = "Wednesday.html#talk_194">R For Everything</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_195">195</a></td><td><a href = "Wednesday.html#talk_195">Tick-By-Tick Effect On The Inference Of Ultra-High Frequency Data</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_196">196</a></td><td><a href = "Wednesday.html#talk_196">A Simple Method To Construct Confidence Bands In Functional Linear Regression</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_197">197</a></td><td><a href = "Wednesday.html#talk_197">Space And Circular Time Log Gaussian Cox Processes With Application To Crime Event Data</a></td></tr>
<tr><td><a href = "Tuesday.html#talk_198">198</a></td><td><a href = "Tuesday.html#talk_198">Could Do Better &hellip; A Report Card For Statistical Computing</a></td></tr>
<tr><td><a href = "Thursday.html#talk_199">199</a></td><td><a href = "Thursday.html#talk_199">ALTREP: Alternate Representations Of Basic R Objects</a></td></tr>
<tr><td><a href = "Monday.html#talk_200">200</a></td><td><a href = "Monday.html#talk_200">Zen And The aRt Of Workflow Maintenance</a></td></tr>
<tr><td><a href = "Monday.html#talk_201">201</a></td><td><a href = "Monday.html#talk_201">R In Times Of Growing User Base And Data Sizes</a></td></tr>
<tr><td><a href = "Wednesday.html#talk_202">202</a></td><td><a href = "Wednesday.html#talk_202">A Bayesian Inference For Time Series Via Copula-Based Markov Chain Models</a></td></tr>
<tr><td><a href = "Monday.html#talk_203">203</a></td><td><a href = "Monday.html#talk_203">Estimating Links Of A Network From Time To Event Data</a></td></tr>
<tr><td><a href = "Monday.html#talk_204">204</a></td><td><a href = "Monday.html#talk_204">E-Learning Courses On Introductory Statistics Using Interactive Educational Tools</a></td></tr>
</tbody>
</table>
