# Am I A Session Chair? Please Read!!! {-}
## Monday {#Monday-chairtbl .unnumbered}
<div style = "overflow-x:auto;">
<table>
<thead>
<tr>
<th class = "time">Time</th>
<th class = "day" colspan = "6">Monday 11<sup>th</sup></th>
</tr>
</thead>
<tbody>
<tr>
<td class = "time">910</td>
<td class = "keynote" colspan = "6"> Wing Kam Fung</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1030</td>
<td class = "contributed">
Han-Ming Wu (National Taipei University, Taiwan)</td>
<td class = "contributed">
Ciprian Doru Giurcaneanu (UOA)</td>
<td class = "contributed">
David Scott (UOA)</td>
<td class = "contributed">
Erniel Barrios (University of Philippines Diliman)</td>
<td class = "contributed">
Jin Liu (Duke-NUS Medical School)</td>
<td class = "contributed">
Junji Nakano (Institute of Statistical Mathematics, Japan) and Yuichi Mori (Okayama University of Science, Japan)</td>
</tr>
<tr>
<td class = "time">1320</td>
<td class = "keynote" colspan = "6"> James Curran</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1410</td>
<td class = "contributed">Han-Ming Wu (National Taipei University, Taiwan)</td>
<td class = "contributed">Thomas Yee (UOA)</td>
<td class = "contributed">Rolf Turner (UOA)</td>
<td class = "contributed">Priya Parmar (AUT)</td>
<td class = "contributed">Ray-Bing Chen (National Cheng Kung University, Taiwan)
and Linlin Niu (Xiamen University, China)</td>
<td class = "contributed">Maxine Pfannkuch (UOA)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1600</td>
<td class = "contributed"></td>
<td class = "contributed">Alan Lee (UOA)</td>
<td class = "contributed">??? (UOA)</td>
<td class = "contributed">Benoit Liquet (University of Pau et Pays de L'Adour)</td>
<td class = "contributed">Hiroyuki Minami (Hokkaido University, Japan)</td>
<td class = "contributed">Matt Parry (University of Otago)</td>
</tr>
</tbody>
</table>
</div>
## Tuesday {#Tuesday-chairtbl .unnumbered}
<div style = "overflow-x:auto;">
<table>
<thead>
<tr>
<th class = "time">Time</th>
<th class = "day" colspan = "6">Tuesday 12<sup>th</sup></th>
</tr>
</thead>
<tbody>
<tr>
<td class = "time">910</td>
<td class = "keynote" colspan = "6"> Paul Murrell</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1030</td>
<td class = "contributed">Xun Xiao (Massey University)</td>
<td class = "contributed">???? Students</td>
<td class = "contributed">???? Students</td>
<td class = "contributed">Geoff Jones (Massey University)</td>
<td class = "contributed">Jaeyong Lee (Seoul National University, Korea)</td>
<td class = "contributed">Catherine Laffineur (Université Côte d'Azur, GREDEG-CNRS)</td>
</tr>
<tr>
<td class = "time">1320</td>
<td class = "keynote" colspan = "6"> Chris Triggs



</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1600</td>
<td class = "contributed">Hsin-Cheng Huang (Academia Sinica, Taiwan)</td>
<td class = "contributed">Russell Millar (UOA)</td>
<td class = "contributed">Philip L.H. Yu (The University of Hong Kong)</td>
<td class = "contributed">Michael Slyuzberg (NZ Ministry of Justice)</td>
<td class = "contributed">Rose Sisk (AUT)</td>
<td class = "contributed">Tanmay Kayal (Indian Institute of Technology Patna)</td>
</tr>
</tbody>
</table>
</div>
## Wednesday {#Wednesday-chairtbl .unnumbered}
<div style = "overflow-x:auto;">
<table>
<thead>
<tr>
<th class = "time">Time</th>
<th class = "day" colspan = "6">Wednesday 13<sup>th</sup></th>
</tr>
</thead>
<tbody>
<tr>
<td class = "time">910</td>
<td class = "keynote" colspan = "6">Professor Michael Ferris, University of Wisconsin - Madison, USA
ORSNZ Keynote
098 Lecture Theatre (260-098)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1030</td>
<td class = "contributed">Paul Murrell (UOA)</td>
<td class = "contributed">
Marco Reale (University of Canterbury)</td>
<td class = "contributed">Toru Ogura (Mie University Hospital)</td>
<td class = "contributed">Kazumi Wada (National Statistics Center, Japan)</td>
<td class = "contributed">Hidetoshi Murakami (Tokyo University of Science)</td>
<td class = "contributed">Blair Robertson (University of Canterbury)</td>
</tr>
<tr>
<td class = "time">1320</td>
<td class = "keynote" colspan = "6"> I am waiting for Renate to accept (or not) the proposal</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">Case Room 1(260-005)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1410</td>
<td class = "contributed">Hiroshi Yadohisa (Doshisha University, Japan)</td>
<td class = "contributed">Donguk Kim (Sungkyunkwan University, Korea)</td>
<td class = "contributed">Chul Eung Kim (Yonsei University, Korea)</td>
<td class = "contributed">Johan Lim (Seoul National University, Korea)</td>
<td class = "contributed">Steven Miller (University of Waikato)</td>
<td class = "contributed">Jinfang Wang (Chiba University, Japan)</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 1(260-005)</td>
</tr>
<tr>
<td class = "time">1600</td>
<td class = "contributed">Martin Hazelton (Massey University)</td>
<td class = "contributed">Andriy Olenko (La Trobe University, Australia)</td>
<td class = "contributed">A New Approach To Distribution Free Tests In Contingency Tables
Thuong Nguyen (Victoria University)</td>
<td class = "contributed">Beatrix Jones (Massey University)</td>
<td class = "contributed">Erniel Barrios (University of the Philippines Diliman)</td>
<td class = "contributed"></td>
</tr>
</tbody>
</table>
</div>
## Thursday {#Thursday-chairtbl .unnumbered}
<div style = "overflow-x:auto;">
<table>
<thead>
<tr>
<th class = "time">Time</th>
<th class = "day" colspan = "6">Thursday 14<sup>th</sup></th>
</tr>
</thead>
<tbody>
<tr>
<td class = "time">910</td>
<td class = "keynote" colspan = "6"> Thomas Yee</td>
</tr>
<tr>
<td class = "time"></td>
<td class = "sessionheader">098 Lecture Theatre(260-098)</td>
<td class = "sessionheader">OGGB4(260-073)</td>
<td class = "sessionheader">OGGB5(260-051)</td>
<td class = "sessionheader">Case Room 2(260-057)</td>
<td class = "sessionheader">Case Room 3(260-055)</td>
<td class = "sessionheader">Case Room 4(260-009)</td>
</tr>
<tr>
<td class = "time">1030</td>
<td class = "contributed">Thomas Yee (UOA)</td>
<td class = "contributed">Yuichi Mori (Okayama University of Science, Japan)</td>
<td class = "contributed">Yoshikazu Yamamoto (Tokushima Bunri University, Japan)</td>
<td class = "contributed">Masahiro Mizuta (Hokkaido University, Japan)</td>
<td class = "contributed">Zehua Chen (National University of Singapore)</td>
<td class = "contributed"></td>
</tr>
</tbody>
</table>
</div>
